Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
  	web.vm.network "private_network", ip: "192.168.61.3"
  	web.vm.hostname = "web.mentorship"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.network "private_network", ip: "192.168.61.4"
  	db.vm.hostname = "db.mentorship"
  end
end
