---
- hosts: servers
  gather_facts: yes
  
- hosts: dc3
  become: yes
  gather_facts: yes
  tasks:
  - name: update cache RedHat
    yum:
      name: '*'

  - name: install packages
    package: name={{item}} state=installed
    with_items:
         - epel-release
         - nginx

  - name: init nginx on boot
    service:
      name: nginx
      enabled: yes

  - name: copy proxy config
    template:
      src: resources/proxy.j2
      dest: /etc/nginx/conf.d/proxy.conf
      backup: yes

  - name: copy nginx.conf
    copy:
      src: resources/nginx.conf
      dest: /etc/nginx/nginx.conf
      force: yes
      mode: 0644
      backup: yes
      validate: nginx -t -c /etc/nginx/nginx.conf

  - uri:
      url: "http://{{ ansible_eth1.ipv4.address }}/"
      follow_redirects: all
      register: webpage
      timeout: 30

  handlers:
   - name: restart nginx
     service: name=nginx state=restarted
     become: yes
