---
- hosts: servers
  gather_facts: yes
  vars_files:
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/Generic.yml"
  vars:
     tomcat_home: "{{ lookup('env','CATALINA_HOME') }}"
  become: yes
  tasks:

  - name: add apt repo for java
    apt_repository:
      repo: ppa:webupd8team/java
    when: ansible_os_family == "Debian"

  - name: update cache Debian
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: update cache RedHat
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"

  - name: install packages
    package: name={{item}} state=installed
    with_items:
         - "{{ java }}"
         - "{{ tomcat }}"

  - name: config Tomcat
    copy:
      src: resources/server.xml
      dest: "{{ CATALINA_HOME }}server.xml"
      owner: "{{ tomcat }}"
      group: "{{ tomcat }}"
      mode: 0644
      backup: yes
    notify:
    - restart tomcat

  - name: download WAR file
    get_url:
      url: https://raw.githubusercontent.com/dimahavrylevych/mentorship/master/vagrant/sample.war
      dest: "{{ CATALINA_WEBAPPS }}ROOT.war"
      checksum: md5:60227f2728e07242a78f2ac0fd74f5ca
      force: yes
      group: "{{ tomcat }}"
      owner: root
      backup: yes
      timeout: 20
    notify:
    - remove ROOT
    - restart tomcat

  - meta: flush_handlers

  - name: init tomcat on boot
    service:
      name: "{{ tomcat }}"
      enabled: yes

  - uri:
      url: "http://{{ ansible_eth1.ipv4.address }}:8080/"
      status_code: 200
      follow_redirects: all
      register: webpage
      until: webpage.status == 200
      retries: 10
      timeout: 120
      delay: 1

  handlers:
   - name: restart tomcat
     service: name="{{ tomcat }}" state=restarted
     become: yes
     environment:
       JAVA_HOME: "{{ java_h }}"
   - name: remove ROOT
     command: rm -rf "{{ CATALINA_WEBAPPS }}/ROOT"
     become: yes
     when: ansible_os_family == "Debian"
