---
- hosts: servers
  become: yes
  tasks:
  - name: Ensure NTP is installed.
    package:
      name: ntp
      state: latest
  - name: Ensure NTP is running (ubuntu).
    service: name=ntp state=started enabled=yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Ensure NTP is running (centos).
    service: name=ntpd state=started enabled=yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
