---
#
- name: generic
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - common

- name: hosts
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - hosts

- name: webserver
  hosts: servers
  gather_facts: yes
  become: yes
  roles:
    - webserver

- name: proxy
  hosts: dc3
  gather_facts: yes
  become: yes
  roles:
    - proxy
