---
#tasks file for common

- name: add apt repo for java
  apt_repository:
   repo: ppa:webupd8team/java
  when: ansible_os_family == "Debian"

- name: install EPEL
  yum:
   name: 'epel-release'
   state: installed
  when: ansible_os_family == "RedHat"
